name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_scan_job:
    runs-on: ubuntu-latest
    name: Security Scan
    steps:
    - uses: actions/checkout@v2
    - name: SAST Scan
      uses: AppThreat/sast-scan-action@master
      with:
        type: "python"
    - uses: actions/upload-artifact@v2
      with:
        name: reports
        path: reports
