name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#on: [push]

jobs:
 salus_scan_job:
   runs-on: ubuntu-latest
   name: Salus Security Scan Example
   steps:
   - uses: actions/checkout@v1
   - name: Salus Scan
     id: salus_scan
     uses: federacy/scan-action@0.1.3
     with:
         active_scanners: "\n  - Bandit"
         enforced_scanners: "\n  - Bandit"
     env:
         SALUS_CONFIGURATION: "file://salus-config.yaml"
#jobs:
#  salus_scan_job:
#    runs-on: ubuntu-latest
#    name: Salus Security Scan Example
#    steps:
#    - uses: actions/checkout@v1
#    - name: Salus Scan
#      id: salus_scan
#      uses: federacy/scan-action@0.1.3
#      with:
#          active_scanners: "\n  - Bandit"
#          enforced_scanners: "\n  - Bandit" 
#      env:	      
#	  SALUS_CONFIGURATION: "file://salus-config.yaml	
 

#jobs:
#  security_scan_job:
#    runs-on: ubuntu-latest
#    name: Security Scan
#    steps:
#    - uses: actions/checkout@v2
#    - name: SAST Scan
#      uses: AppThreat/sast-scan-action@master
#      with:
#        type: "python"
#    - uses: actions/upload-artifact@v2
#      with:
#        name: reports
#        path: reports
